/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export function version(): string
export function doneSourcingData(): void
export function setDataForSlug(userInput: string): Promise<void>
export function incremental(inputDir: string, outputDir: string): Promise<Array<string>>
